"""Data-query tools for the ThoughtSpot API.

Covers the three "Data" endpoints of REST API v2.0:
    - thoughtspot_search_data: POST /searchdata (TML search syntax over a
      Worksheet, View, Table, or SQL view).
    - thoughtspot_get_liveboard_data: POST /metadata/liveboard/data.
    - thoughtspot_get_answer_data: POST /metadata/answer/data.

All three share the same pagination (record_offset/record_size) and runtime
override (filter/sort/param) shape. ``data_rows`` items are documented as
generic objects; observed shapes vary between a dict keyed by column name and
a plain list, so rendering normalises via ``_row_values``. Result sets are
capped at ``MAX_DISPLAY_ROWS`` to protect the LLM context window even when a
caller requests a larger page (airbyte-mcp's log-truncation pattern).
"""

from __future__ import annotations

from typing import Any, Literal

from mcp.types import ToolAnnotations
from pydantic import BaseModel, ConfigDict, Field

from thoughtspot_mcp.client import get_client
from thoughtspot_mcp.errors import handle_api_error
from thoughtspot_mcp.formatters import ResponseFormat, to_json, truncate_records
from thoughtspot_mcp.server import mcp

# Rows rendered per response, independent of the API-level record_size page.
# A second, tighter safety net for wide/verbose result sets (e.g. data_format=FULL).
MAX_DISPLAY_ROWS = 50


# ---------------------------------------------------------------------------
# Input models
# ---------------------------------------------------------------------------


class _DataQueryFields(BaseModel):
    """Fields shared by all three data-query tools."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    data_format: Literal["COMPACT", "FULL"] = Field(
        default="COMPACT",
        description="JSON output shape. FULL is only available on 9.12.5.cl or later.",
    )
    record_offset: int = Field(default=0, ge=0, description="Starting record number for this page.")
    record_size: int = Field(
        default=50,
        ge=1,
        le=500,
        description="Records to fetch in this page (ThoughtSpot's own API default is 10).",
    )
    runtime_filter: dict[str, Any] | None = Field(
        default=None,
        description="Runtime filter override, e.g. {'col1': 'item type', 'op1': 'EQ', 'val1': 'Bags'}.",
    )
    runtime_sort: dict[str, Any] | None = Field(
        default=None,
        description="Runtime sort override, e.g. {'sortCol1': 'sales', 'asc1': True}.",
    )
    runtime_param_override: dict[str, Any] | None = Field(
        default=None,
        description="Runtime parameter override, e.g. {'param1': 'Double List Param', 'paramVal1': 0.5}.",
    )
    response_format: ResponseFormat = Field(default=ResponseFormat.MARKDOWN)

    def to_body(self) -> dict[str, Any]:
        """Common request-body fields, omitting unset runtime overrides."""
        body: dict[str, Any] = {
            "data_format": self.data_format,
            "record_offset": self.record_offset,
            "record_size": self.record_size,
        }
        if self.runtime_filter is not None:
            body["runtime_filter"] = self.runtime_filter
        if self.runtime_sort is not None:
            body["runtime_sort"] = self.runtime_sort
        if self.runtime_param_override is not None:
            body["runtime_param_override"] = self.runtime_param_override
        return body


class SearchDataInput(_DataQueryFields):
    query_string: str = Field(..., min_length=1, description="TML search tokens, e.g. '[sales] by [store]'.")
    logical_table_identifier: str = Field(
        ...,
        min_length=1,
        description="GUID or name of the data source object (Worksheet, View, Table, or SQL view).",
    )


class GetLiveboardDataInput(_DataQueryFields):
    metadata_identifier: str = Field(..., min_length=1, description="GUID or name of the Liveboard.")
    visualization_identifiers: list[str] | None = Field(
        default=None,
        description="GUIDs or names of specific visualizations to fetch. Omit to fetch all of them.",
    )
    transient_content: str | None = Field(
        default=None,
        description=(
            "Transient Liveboard content generated by the Visual Embed SDK's "
            "getExportRequestForCurrentPinboard, to include unsaved changes such as "
            "sorting, legend toggles, or drill-downs."
        ),
    )


class GetAnswerDataInput(_DataQueryFields):
    metadata_identifier: str = Field(..., min_length=1, description="GUID or name of the saved Answer.")


# ---------------------------------------------------------------------------
# Formatters
# ---------------------------------------------------------------------------


def _row_values(row: Any, column_names: list[str]) -> list[Any]:
    """Normalise a data_rows entry to a positional list of cell values.

    data_rows items are typed as generic objects in the OpenAPI spec;
    observed shapes vary between a dict keyed by column name and a plain list.
    """
    if isinstance(row, list):
        return row
    if isinstance(row, dict):
        if column_names and all(c in row for c in column_names):
            return [row[c] for c in column_names]
        return list(row.values())
    return [row]


def _cell(value: Any) -> str:
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\n", " ")


def _fmt_content(content: dict[str, Any], *, heading: str) -> str:
    column_names = content.get("column_names", [])
    rows = content.get("data_rows", [])
    shown, truncated = truncate_records(rows, MAX_DISPLAY_ROWS)

    lines = [f"### {heading}"]
    lines.append(
        f"- Rows returned: **{content.get('returned_data_row_count', len(rows))}** "
        f"(available: **{content.get('available_data_row_count', '?')}**, "
        f"sampling ratio: **{content.get('sampling_ratio', 1.0)}**)"
    )
    if column_names:
        lines.append("")
        lines.append("| " + " | ".join(column_names) + " |")
        lines.append("| " + " | ".join(["---"] * len(column_names)) + " |")
        for row in shown:
            lines.append("| " + " | ".join(_cell(v) for v in _row_values(row, column_names)) + " |")
    if truncated:
        lines.append("")
        lines.append(
            f"_Display truncated to the first {MAX_DISPLAY_ROWS} of {len(rows)} rows in this page. "
            "Use record_offset to page further._"
        )
    lines.append("")
    return "\n".join(lines)


def _truncate_for_json(contents: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], bool]:
    any_truncated = False
    out: list[dict[str, Any]] = []
    for content in contents:
        rows = content.get("data_rows", [])
        shown, truncated = truncate_records(rows, MAX_DISPLAY_ROWS)
        any_truncated = any_truncated or truncated
        out.append({**content, "data_rows": shown})
    return out, any_truncated


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------


@mcp.tool(
    name="thoughtspot_search_data",
    annotations=ToolAnnotations(
        title="Search ThoughtSpot Data",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
async def thoughtspot_search_data(params: SearchDataInput) -> str:
    """Run a TML search query against a Worksheet, View, Table, or SQL view.

    Requires at least view access to the data source; if RBAC is enabled, also
    requires the "Can download detailed data" privilege.

    When to Use:
        - Ad hoc data exploration without a saved Answer or Liveboard, e.g.
          "[sales] by [store]".
        - Programmatic access to a metric broken down by one or more attributes.

    When NOT to Use:
        - To re-fetch an already-saved Answer, use thoughtspot_get_answer_data
          (avoids re-parsing the search string).
        - To fetch a Liveboard visualization's data, use
          thoughtspot_get_liveboard_data.

    Returns:
        Column names and rows for the query. Markdown renders a table capped
        at 50 rows per call (page further with record_offset); JSON returns
        the same capped rows plus a display_truncated flag.

    Examples:
        Basic usage:
            params = {
                "query_string": "[sales] by [store]",
                "logical_table_identifier": "cd252e5c-b552-49a8-821d-3eadaa049cca",
            }
        With a runtime filter:
            params = {
                "query_string": "[sales] by [item type]",
                "logical_table_identifier": "cd252e5c-...",
                "runtime_filter": {"col1": "item type", "op1": "EQ", "val1": "Bags"},
            }

    Error Handling:
        400 usually means an invalid query_string or logical_table_identifier;
        403 means missing view/download privileges on the data source.
    """
    try:
        client = get_client()
        body: dict[str, Any] = {
            "query_string": params.query_string,
            "logical_table_identifier": params.logical_table_identifier,
            **params.to_body(),
        }
        resp = await client.request("POST", "/searchdata", json_body=body)
        data = resp.json()
        contents: list[dict[str, Any]] = data.get("contents", [])

        if params.response_format == ResponseFormat.JSON:
            shown, truncated = _truncate_for_json(contents)
            return to_json({"contents": shown, "display_truncated": truncated})

        if not contents:
            return "No data returned for this query."

        return "\n".join(_fmt_content(c, heading="Search Results") for c in contents)
    except Exception as exc:
        return handle_api_error(exc)


@mcp.tool(
    name="thoughtspot_get_liveboard_data",
    annotations=ToolAnnotations(
        title="Get ThoughtSpot Liveboard Data",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
async def thoughtspot_get_liveboard_data(params: GetLiveboardDataInput) -> str:
    """Get the data behind a Liveboard's visualizations.

    Requires at least view access to the Liveboard; if RBAC is enabled, also
    requires the "Can download detailed data" privilege.

    When to Use:
        - Pull the underlying rows for one or more charts on a Liveboard.
        - Include unsaved changes (sort, legend toggles, drill-downs) via
          transient_content generated by the Visual Embed SDK.

    When NOT to Use:
        - To render the Liveboard visually, use thoughtspot_export_liveboard_report
          (PDF/PNG/CSV/XLSX) instead.
        - To fetch a standalone Answer's data, use thoughtspot_get_answer_data.

    Returns:
        One section per visualization with column names and rows. Markdown
        renders a table per visualization capped at 50 rows per call (page
        further with record_offset); JSON returns the same capped rows plus a
        display_truncated flag.

    Examples:
        All visualizations on a Liveboard:
            params = {"metadata_identifier": "a1b2c3d4-..."}
        Specific visualizations only:
            params = {
                "metadata_identifier": "a1b2c3d4-...",
                "visualization_identifiers": ["viz-guid-1", "viz-guid-2"],
            }

    Error Handling:
        404 means the Liveboard GUID/name was not found; 403 means missing
        view/download privileges.
    """
    try:
        client = get_client()
        body: dict[str, Any] = {
            "metadata_identifier": params.metadata_identifier,
            **params.to_body(),
        }
        if params.visualization_identifiers is not None:
            body["visualization_identifiers"] = params.visualization_identifiers
        if params.transient_content is not None:
            body["transient_content"] = params.transient_content

        resp = await client.request("POST", "/metadata/liveboard/data", json_body=body)
        data = resp.json()
        metadata_name = data.get("metadata_name", params.metadata_identifier)
        metadata_id = data.get("metadata_id", params.metadata_identifier)
        contents: list[dict[str, Any]] = data.get("contents", [])

        if params.response_format == ResponseFormat.JSON:
            shown, truncated = _truncate_for_json(contents)
            return to_json(
                {
                    "metadata_id": metadata_id,
                    "metadata_name": metadata_name,
                    "contents": shown,
                    "display_truncated": truncated,
                }
            )

        if not contents:
            return f"No data returned for Liveboard **{metadata_name}** ({metadata_id})."

        sections = [
            _fmt_content(c, heading=c.get("visualization_name") or c.get("visualization_id") or "Visualization")
            for c in contents
        ]
        return f"# {metadata_name} ({metadata_id})\n\n" + "\n".join(sections)
    except Exception as exc:
        return handle_api_error(exc)


@mcp.tool(
    name="thoughtspot_get_answer_data",
    annotations=ToolAnnotations(
        title="Get ThoughtSpot Answer Data",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
async def thoughtspot_get_answer_data(params: GetAnswerDataInput) -> str:
    """Get the data behind a saved Answer.

    Requires at least view access to the Answer; if RBAC is enabled, also
    requires the "Can download detailed data" privilege.

    When to Use:
        - Pull the underlying rows for a saved Answer by GUID or name.

    When NOT to Use:
        - For ad hoc queries with no saved Answer, use thoughtspot_search_data.
        - For a Liveboard visualization's data, use thoughtspot_get_liveboard_data.

    Returns:
        Column names and rows for the Answer. Markdown renders a table capped
        at 50 rows per call (page further with record_offset); JSON returns
        the same capped rows plus a display_truncated flag.

    Examples:
        Basic usage:
            params = {"metadata_identifier": "a1b2c3d4-..."}

    Error Handling:
        404 means the Answer GUID/name was not found; 403 means missing
        view/download privileges.
    """
    try:
        client = get_client()
        body: dict[str, Any] = {
            "metadata_identifier": params.metadata_identifier,
            **params.to_body(),
        }
        resp = await client.request("POST", "/metadata/answer/data", json_body=body)
        data = resp.json()
        metadata_name = data.get("metadata_name", params.metadata_identifier)
        metadata_id = data.get("metadata_id", params.metadata_identifier)
        contents: list[dict[str, Any]] = data.get("contents", [])

        if params.response_format == ResponseFormat.JSON:
            shown, truncated = _truncate_for_json(contents)
            return to_json(
                {
                    "metadata_id": metadata_id,
                    "metadata_name": metadata_name,
                    "contents": shown,
                    "display_truncated": truncated,
                }
            )

        if not contents:
            return f"No data returned for Answer **{metadata_name}** ({metadata_id})."

        sections = [_fmt_content(c, heading=metadata_name) for c in contents]
        return f"# {metadata_name} ({metadata_id})\n\n" + "\n".join(sections)
    except Exception as exc:
        return handle_api_error(exc)
