name: Publish to PyPI

on:
  release:
    types: [ published ]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish
